project:
  type: website
  output-dir: docs

website:
  title: "Knit, Purl, Code"
  navbar:
    right:
      - about.qmd
format:
  html:
    theme:
      - litera
      - brand
    css: styles.css

# Set the posts page as the home page
home: posts/intro_knitting_stats/post_intro.qmd

